version: '3.7'

services:
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: server
    ports:
      - 5001:5000
    volumes:
      - ./server:/usr/app  # Mount server directory for live reloading
    depends_on:
      - frontend  # Wait for frontend to be ready
  frontend:
    build:
      context: cognate-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/app  # Mount client directory for live reloading